# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataByYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('coal', models.IntegerField()),
                ('natural_gas', models.IntegerField()),
                ('petroleum', models.IntegerField()),
                ('nuclear', models.IntegerField()),
                ('fuel_ethanol_production_losses', models.IntegerField()),
                ('fuel_ethanol', models.IntegerField()),
                ('geothermal', models.IntegerField()),
                ('hydropower', models.IntegerField()),
                ('solar', models.IntegerField()),
                ('wood_and_waste', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('international_imports', models.IntegerField()),
                ('interstate_imports_exports', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_full_name', models.CharField(max_length=50)),
                ('state_abbrev_name', models.CharField(max_length=50)),
                ('state_geometry', models.CharField(max_length=50)),
                ('state_data_by_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_stats.DataByYear')),
            ],
        ),
    ]
