# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_row_id', models.IntegerField()),
                ('data_status', models.CharField(max_length=5, verbose_name='Date data was last updated')),
                ('msn', models.CharField(max_length=5, verbose_name='Data Series Names')),
                ('statecode', models.CharField(max_length=2)),
                ('year', models.IntegerField(max_length=4)),
                ('data', models.FloatField(verbose_name='Value for given MSN. Units may vary')),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_data_by_year',
        ),
        migrations.DeleteModel(
            name='DataByYear',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
