# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0002_auto_20170215_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.IntegerField(),
        ),
    ]
