# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0003_auto_20170215_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('msn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_stats.Data', unique=True)),
            ],
        ),
    ]
