# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='msn',
            field=models.CharField(max_length=5, verbose_name='Data Series Names'),
        ),
    ]
