# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0004_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statecode', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('re_over_te', models.FloatField(verbose_name='renewable total over total')),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='msn',
            field=models.CharField(max_length=5, verbose_name='Data Series Names'),
        ),
    ]
