# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0005_auto_20170307_1153'),
        ('re_stats', '0005_auto_20170321_2222'),
    ]

    operations = [
    ]
