# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0006_merge_20170322_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapData',
        ),
    ]
