# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0009_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='features',
            new_name='ALAND10',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='type',
            new_name='AWATER10',
        ),
        migrations.AddField(
            model_name='map',
            name='INTPTLAT10',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='INTPTLON10',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='coordinates',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='fid',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='geometry',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='state_label',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='statecode',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
