# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0009_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
