# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('re_stats', '0010_delete_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionByYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_rank', models.IntegerField()),
                ('year', models.IntegerField()),
                ('last_updated', models.DateField(verbose_name='Date data was last updated')),
                ('total_energy_consumption', models.FloatField()),
                ('fossil_fuels_total_consumption', models.FloatField()),
                ('coal_total_consumption', models.FloatField()),
                ('natural_gas_total_consumption', models.FloatField()),
                ('petroleum_total_consumption', models.FloatField()),
                ('nuclear_total_consumption', models.FloatField()),
                ('renewable_energy_total_consumption', models.FloatField()),
                ('fuel_ethanol_production_losses', models.FloatField()),
                ('fuel_ethanol_total_consumption', models.FloatField()),
                ('geothermal_total_consumption', models.FloatField()),
                ('hydropower_total_consumption', models.FloatField()),
                ('solar_total_consumption', models.FloatField()),
                ('wood_and_waste_total_consumption', models.FloatField()),
                ('wind_total_consumption', models.FloatField()),
                ('net_international_imports', models.FloatField()),
                ('net_interstate_imports', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='MapData',
        ),
        migrations.AddField(
            model_name='consumptionbyyear',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='re_stats.State'),
        ),
    ]
